name: E2E

on:
  pull_request:
  # push:
  #   branches: [main]  # Temporarily disabled until E2E is stable
  workflow_dispatch:  # Manual trigger for testing

jobs:
  e2e:
    runs-on: ubuntu-latest

    env:
      NEXTAUTH_SECRET: test-secret
      # BASE_URL used by Playwright config; points to webServer
      BASE_URL: http://localhost:3000

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies (include dev)
        run: npm ci

      - name: Generate Prisma client
        run: npx prisma generate

      # Build step is handled by Playwright webServer via npm run test:e2e:start

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          ZOTERO_GROUP_ID: ${{ secrets.ZOTERO_GROUP_ID }}
          ZOTERO_API_KEY: ${{ secrets.ZOTERO_API_KEY }}
        run: npx playwright test

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 7

      - name: Upload test-results (traces/videos)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results
          retention-days: 7
