name: E2E

on:
  pull_request:
  # push:
  #   branches: [main]  # Temporarily disabled until E2E is stable
  workflow_dispatch:  # Manual trigger for testing

jobs:
  e2e:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: athanor_test
        ports: ['5432:5432']
        options: >-
          --health-cmd="pg_isready -U postgres -d athanor_test"
          --health-interval=10s --health-timeout=5s --health-retries=5

    env:
      BASE_URL: http://localhost:3000
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
      ZOTERO_GROUP_ID: ${{ secrets.ZOTERO_GROUP_ID }}
      ZOTERO_API_KEY: ${{ secrets.ZOTERO_API_KEY }}
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/athanor_test
      DIRECT_DATABASE_URL: postgresql://postgres:postgres@localhost:5432/athanor_test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies (include dev)
        run: npm ci

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Prepare DB schema (migrate deploy)
        run: npx prisma migrate deploy

      # Build step is handled by Playwright webServer via npm run test:e2e:start

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 7

      - name: Upload test-results (traces/videos)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results
          retention-days: 7
